## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

2025-01-13 09:29:19.142774: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition','Department']]
y_df.head()

  Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [4]:
# Create a list of at least 10 column names to use as X data
X_columns_list = ['Age','DistanceFromHome','EnvironmentSatisfaction','HourlyRate','JobInvolvement','JobSatisfaction','TotalWorkingYears','WorkLifeBalance','YearsInCurrentRole','YearsSinceLastPromotion']

# Create X_df using your selected columns
X_df = attrition_df[X_columns_list]

# Show the data types for X_df
X_df.dtypes

Age                        int64
DistanceFromHome           int64
EnvironmentSatisfaction    int64
HourlyRate                 int64
JobInvolvement             int64
JobSatisfaction            int64
TotalWorkingYears          int64
WorkLifeBalance            int64
YearsInCurrentRole         int64
YearsSinceLastPromotion    int64
dtype: object

In [5]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=78)

In [6]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
attrition_df["OverTime"].value_counts()

(1102, 10) (368, 10) (1102, 2) (368, 2)

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [7]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
X_scaler = scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [ ]:
# Create a OneHotEncoder for the Department column
from sklearn.preprocessing import OneHotEncoder

ohe_dept = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
ohe_dept.fit(y_train['Department'].values.reshape(-1,1))

# Create two new variables by applying the encoder
# to the training and testing data
train_dept_encoded = ohe_dept.transform(y_train['Department'].values.reshape(-1,1))
test_dept_encoded = ohe_dept.transform(y_test['Department'].values.reshape(-1,1))
train_dept_encoded

array([[0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [9]:
# Create a OneHotEncoder for the Attrition column
ohe_attr = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
ohe_attr.fit(y_train['Attrition'].values.reshape(-1,1))

# Create two new variables by applying the encoder
# to the training and testing data
train_attr_encoded = ohe_attr.transform(y_train['Attrition'].values.reshape(-1,1))
test_attr_encoded = ohe_attr.transform(y_test['Attrition'].values.reshape(-1,1))
train_attr_encoded

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [0., 1.]])

## Create, Compile, and Train the Model

In [10]:
# Find the number of columns in the X training data
num_columns = X_train.shape[1]

# Create the input layer
input_layer = layers.Input(shape = (num_columns,))

# Create at least two shared layers
shared_layer1 = layers.Dense(64, activation='relu', name='Shared_1')(input_layer)
shared_layer2 = layers.Dense(32, activation='relu', name='Shared_2')(shared_layer1)

In [12]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
dept_hidden_layer1 = layers.Dense(32, activation='relu', name = 'dept_hidden')(shared_layer2)

# Create the output layer
dept_output_layer1 = layers.Dense(units=train_dept_encoded.shape[1], activation='softmax', name = 'dept_output')(dept_hidden_layer1)

In [14]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attr_hidden_layer2 = layers.Dense(32, activation='relu', name = 'attr_hidden')(shared_layer2)

# Create the output layer
attr_output_layer2 = layers.Dense(units=train_attr_encoded.shape[1], activation='sigmoid', name = 'attr_output')(attr_hidden_layer2)

In [18]:
# Create the model
model = Model(inputs=input_layer, outputs=[dept_output_layer1, attr_output_layer2])

# Compile the model
model.compile(optimizer='adam',
              loss={'dept_output': 'categorical_crossentropy', 'attr_output': 'binary_crossentropy'},
              metrics={'dept_output':'accuracy', 'attr_output':'accuracy'})

# Summarize the model
model.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 10)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Shared_1 (Dense)    │ (None, 64)        │        704 │ input_layer[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ Shared_2 (Dense)    │ (None, 32)        │      2,080 │ Shared_1[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dept_hidden (Dense) │ (None, 32)        │      1,056 │ Shared_2[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attr_hidden (Dense) │ (None, 32)        │      1,056 │ Shared_2[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dept_output (Dense) │ (None, 3)         │         99 │ dept_hidden[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attr_output (Dense) │ (None, 2)         │         66 │ attr_hidden[0][0] │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 5,061 (19.77 KB)

 Trainable params: 5,061 (19.77 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
# Train the model
model.fit(X_train_scaled, {'dept_output': train_dept_encoded, 'attr_output': train_attr_encoded}, epochs=100, shuffle=True, verbose=2)

Epoch 1/100
35/35 - 5s - 130ms/step - attr_output_accuracy: 0.7069 - attr_output_loss: 0.6393 - dept_output_accuracy: 0.5508 - dept_output_loss: 0.9792 - loss: 1.6196
Epoch 2/100
35/35 - 0s - 7ms/step - attr_output_accuracy: 0.8276 - attr_output_loss: 0.4810 - dept_output_accuracy: 0.6661 - dept_output_loss: 0.7909 - loss: 1.2700
Epoch 3/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8276 - attr_output_loss: 0.4394 - dept_output_accuracy: 0.6661 - dept_output_loss: 0.7650 - loss: 1.2063
Epoch 4/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8276 - attr_output_loss: 0.4288 - dept_output_accuracy: 0.6661 - dept_output_loss: 0.7627 - loss: 1.1823
Epoch 5/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8348 - attr_output_loss: 0.4161 - dept_output_accuracy: 0.6661 - dept_output_loss: 0.7535 - loss: 1.1658
Epoch 6/100
35/35 - 0s - 7ms/step - attr_output_accuracy: 0.8394 - attr_output_loss: 0.4104 - dept_output_accuracy: 0.6652 - dept_output_loss: 0.7455 - loss: 1.1516
Epoch 7/100
35/35 - 0s - 8ms/step - attr_output_accuracy: 0.8376 - attr_output_loss: 0.4027 - dept_output_accuracy: 0.6661 - dept_output_loss: 0.7401 - loss: 1.1424
Epoch 8/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8430 - attr_output_loss: 0.3922 - dept_output_accuracy: 0.6661 - dept_output_loss: 0.7316 - loss: 1.1308
Epoch 9/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8394 - attr_output_loss: 0.3902 - dept_output_accuracy: 0.6670 - dept_output_loss: 0.7310 - loss: 1.1229
Epoch 10/100
35/35 - 1s - 18ms/step - attr_output_accuracy: 0.8412 - attr_output_loss: 0.3861 - dept_output_accuracy: 0.6661 - dept_output_loss: 0.7228 - loss: 1.1131
Epoch 11/100
35/35 - 0s - 8ms/step - attr_output_accuracy: 0.8475 - attr_output_loss: 0.3832 - dept_output_accuracy: 0.6679 - dept_output_loss: 0.7199 - loss: 1.1027
Epoch 12/100
35/35 - 0s - 10ms/step - attr_output_accuracy: 0.8457 - attr_output_loss: 0.3832 - dept_output_accuracy: 0.6679 - dept_output_loss: 0.7190 - loss: 1.0977
Epoch 13/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8439 - attr_output_loss: 0.3813 - dept_output_accuracy: 0.6661 - dept_output_loss: 0.7210 - loss: 1.0945
Epoch 14/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8457 - attr_output_loss: 0.3734 - dept_output_accuracy: 0.6733 - dept_output_loss: 0.7125 - loss: 1.0856
Epoch 15/100
35/35 - 0s - 9ms/step - attr_output_accuracy: 0.8421 - attr_output_loss: 0.3679 - dept_output_accuracy: 0.6751 - dept_output_loss: 0.7094 - loss: 1.0772
Epoch 16/100
35/35 - 0s - 7ms/step - attr_output_accuracy: 0.8475 - attr_output_loss: 0.3643 - dept_output_accuracy: 0.6760 - dept_output_loss: 0.7003 - loss: 1.0661
Epoch 17/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8403 - attr_output_loss: 0.3639 - dept_output_accuracy: 0.6697 - dept_output_loss: 0.7007 - loss: 1.0588
Epoch 18/100
35/35 - 0s - 7ms/step - attr_output_accuracy: 0.8439 - attr_output_loss: 0.3604 - dept_output_accuracy: 0.6797 - dept_output_loss: 0.6864 - loss: 1.0540
Epoch 19/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8457 - attr_output_loss: 0.3653 - dept_output_accuracy: 0.6779 - dept_output_loss: 0.6841 - loss: 1.0430
Epoch 20/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8485 - attr_output_loss: 0.3554 - dept_output_accuracy: 0.6779 - dept_output_loss: 0.6796 - loss: 1.0312
Epoch 21/100
35/35 - 0s - 12ms/step - attr_output_accuracy: 0.8494 - attr_output_loss: 0.3503 - dept_output_accuracy: 0.6897 - dept_output_loss: 0.6712 - loss: 1.0248
Epoch 22/100
35/35 - 0s - 10ms/step - attr_output_accuracy: 0.8521 - attr_output_loss: 0.3519 - dept_output_accuracy: 0.6860 - dept_output_loss: 0.6705 - loss: 1.0184
Epoch 23/100
35/35 - 1s - 16ms/step - attr_output_accuracy: 0.8475 - attr_output_loss: 0.3528 - dept_output_accuracy: 0.6860 - dept_output_loss: 0.6620 - loss: 1.0116
Epoch 24/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8503 - attr_output_loss: 0.3464 - dept_output_accuracy: 0.6878 - dept_output_loss: 0.6591 - loss: 0.9991
Epoch 25/100
35/35 - 1s - 16ms/step - attr_output_accuracy: 0.8530 - attr_output_loss: 0.3411 - dept_output_accuracy: 0.6933 - dept_output_loss: 0.6544 - loss: 0.9930
Epoch 26/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8530 - attr_output_loss: 0.3372 - dept_output_accuracy: 0.6951 - dept_output_loss: 0.6491 - loss: 0.9864
Epoch 27/100
35/35 - 0s - 11ms/step - attr_output_accuracy: 0.8557 - attr_output_loss: 0.3355 - dept_output_accuracy: 0.7060 - dept_output_loss: 0.6370 - loss: 0.9715
Epoch 28/100
35/35 - 1s - 16ms/step - attr_output_accuracy: 0.8548 - attr_output_loss: 0.3323 - dept_output_accuracy: 0.7033 - dept_output_loss: 0.6345 - loss: 0.9650
Epoch 29/100
35/35 - 1s - 35ms/step - attr_output_accuracy: 0.8575 - attr_output_loss: 0.3291 - dept_output_accuracy: 0.7223 - dept_output_loss: 0.6226 - loss: 0.9532
Epoch 30/100
35/35 - 0s - 12ms/step - attr_output_accuracy: 0.8639 - attr_output_loss: 0.3250 - dept_output_accuracy: 0.7187 - dept_output_loss: 0.6188 - loss: 0.9420
Epoch 31/100
35/35 - 1s - 24ms/step - attr_output_accuracy: 0.8621 - attr_output_loss: 0.3226 - dept_output_accuracy: 0.7287 - dept_output_loss: 0.6123 - loss: 0.9330
Epoch 32/100
35/35 - 1s - 17ms/step - attr_output_accuracy: 0.8630 - attr_output_loss: 0.3171 - dept_output_accuracy: 0.7269 - dept_output_loss: 0.6103 - loss: 0.9289
Epoch 33/100
35/35 - 1s - 29ms/step - attr_output_accuracy: 0.8639 - attr_output_loss: 0.3147 - dept_output_accuracy: 0.7432 - dept_output_loss: 0.5967 - loss: 0.9112
Epoch 34/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8657 - attr_output_loss: 0.3107 - dept_output_accuracy: 0.7377 - dept_output_loss: 0.5850 - loss: 0.9021
Epoch 35/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8684 - attr_output_loss: 0.3068 - dept_output_accuracy: 0.7432 - dept_output_loss: 0.5804 - loss: 0.8914
Epoch 36/100
35/35 - 0s - 10ms/step - attr_output_accuracy: 0.8675 - attr_output_loss: 0.3032 - dept_output_accuracy: 0.7523 - dept_output_loss: 0.5740 - loss: 0.8794
Epoch 37/100
35/35 - 0s - 13ms/step - attr_output_accuracy: 0.8684 - attr_output_loss: 0.3055 - dept_output_accuracy: 0.7550 - dept_output_loss: 0.5675 - loss: 0.8727
Epoch 38/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8757 - attr_output_loss: 0.2993 - dept_output_accuracy: 0.7577 - dept_output_loss: 0.5639 - loss: 0.8587
Epoch 39/100
35/35 - 0s - 8ms/step - attr_output_accuracy: 0.8711 - attr_output_loss: 0.2935 - dept_output_accuracy: 0.7650 - dept_output_loss: 0.5524 - loss: 0.8467
Epoch 40/100
35/35 - 0s - 8ms/step - attr_output_accuracy: 0.8757 - attr_output_loss: 0.2911 - dept_output_accuracy: 0.7713 - dept_output_loss: 0.5462 - loss: 0.8381
Epoch 41/100
35/35 - 0s - 7ms/step - attr_output_accuracy: 0.8838 - attr_output_loss: 0.2862 - dept_output_accuracy: 0.7713 - dept_output_loss: 0.5398 - loss: 0.8259
Epoch 42/100
35/35 - 1s - 29ms/step - attr_output_accuracy: 0.8811 - attr_output_loss: 0.2798 - dept_output_accuracy: 0.7713 - dept_output_loss: 0.5340 - loss: 0.8180
Epoch 43/100
35/35 - 0s - 8ms/step - attr_output_accuracy: 0.8784 - attr_output_loss: 0.2834 - dept_output_accuracy: 0.7858 - dept_output_loss: 0.5236 - loss: 0.8081
Epoch 44/100
35/35 - 0s - 10ms/step - attr_output_accuracy: 0.8820 - attr_output_loss: 0.2754 - dept_output_accuracy: 0.7786 - dept_output_loss: 0.5245 - loss: 0.7986
Epoch 45/100
35/35 - 1s - 18ms/step - attr_output_accuracy: 0.8811 - attr_output_loss: 0.2754 - dept_output_accuracy: 0.7886 - dept_output_loss: 0.5115 - loss: 0.7904
Epoch 46/100
35/35 - 1s - 16ms/step - attr_output_accuracy: 0.8838 - attr_output_loss: 0.2687 - dept_output_accuracy: 0.7877 - dept_output_loss: 0.5019 - loss: 0.7743
Epoch 47/100
35/35 - 0s - 14ms/step - attr_output_accuracy: 0.8838 - attr_output_loss: 0.2705 - dept_output_accuracy: 0.8004 - dept_output_loss: 0.4922 - loss: 0.7609
Epoch 48/100
35/35 - 0s - 11ms/step - attr_output_accuracy: 0.8848 - attr_output_loss: 0.2639 - dept_output_accuracy: 0.7976 - dept_output_loss: 0.4871 - loss: 0.7507
Epoch 49/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8866 - attr_output_loss: 0.2576 - dept_output_accuracy: 0.8076 - dept_output_loss: 0.4795 - loss: 0.7387
Epoch 50/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8893 - attr_output_loss: 0.2605 - dept_output_accuracy: 0.8094 - dept_output_loss: 0.4720 - loss: 0.7349
Epoch 51/100
35/35 - 0s - 8ms/step - attr_output_accuracy: 0.8929 - attr_output_loss: 0.2528 - dept_output_accuracy: 0.8113 - dept_output_loss: 0.4641 - loss: 0.7214
Epoch 52/100
35/35 - 0s - 8ms/step - attr_output_accuracy: 0.8920 - attr_output_loss: 0.2524 - dept_output_accuracy: 0.8067 - dept_output_loss: 0.4573 - loss: 0.7075
Epoch 53/100
35/35 - 0s - 7ms/step - attr_output_accuracy: 0.8920 - attr_output_loss: 0.2475 - dept_output_accuracy: 0.8140 - dept_output_loss: 0.4511 - loss: 0.7001
Epoch 54/100
35/35 - 0s - 9ms/step - attr_output_accuracy: 0.9011 - attr_output_loss: 0.2398 - dept_output_accuracy: 0.8194 - dept_output_loss: 0.4408 - loss: 0.6852
Epoch 55/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8938 - attr_output_loss: 0.2388 - dept_output_accuracy: 0.8230 - dept_output_loss: 0.4392 - loss: 0.6756
Epoch 56/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.8902 - attr_output_loss: 0.2356 - dept_output_accuracy: 0.8285 - dept_output_loss: 0.4296 - loss: 0.6668
Epoch 57/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9011 - attr_output_loss: 0.2339 - dept_output_accuracy: 0.8276 - dept_output_loss: 0.4271 - loss: 0.6613
Epoch 58/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9002 - attr_output_loss: 0.2343 - dept_output_accuracy: 0.8403 - dept_output_loss: 0.4213 - loss: 0.6503
Epoch 59/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9047 - attr_output_loss: 0.2253 - dept_output_accuracy: 0.8348 - dept_output_loss: 0.4112 - loss: 0.6397
Epoch 60/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9083 - attr_output_loss: 0.2208 - dept_output_accuracy: 0.8394 - dept_output_loss: 0.4112 - loss: 0.6306
Epoch 61/100
35/35 - 1s - 15ms/step - attr_output_accuracy: 0.9083 - attr_output_loss: 0.2183 - dept_output_accuracy: 0.8376 - dept_output_loss: 0.3983 - loss: 0.6183
Epoch 62/100
35/35 - 1s - 16ms/step - attr_output_accuracy: 0.9093 - attr_output_loss: 0.2151 - dept_output_accuracy: 0.8494 - dept_output_loss: 0.3964 - loss: 0.6115
Epoch 63/100
35/35 - 0s - 10ms/step - attr_output_accuracy: 0.9129 - attr_output_loss: 0.2099 - dept_output_accuracy: 0.8394 - dept_output_loss: 0.4065 - loss: 0.6182
Epoch 64/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9065 - attr_output_loss: 0.2112 - dept_output_accuracy: 0.8539 - dept_output_loss: 0.3914 - loss: 0.5978
Epoch 65/100
35/35 - 0s - 10ms/step - attr_output_accuracy: 0.9165 - attr_output_loss: 0.2039 - dept_output_accuracy: 0.8512 - dept_output_loss: 0.3781 - loss: 0.5833
Epoch 66/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9174 - attr_output_loss: 0.2049 - dept_output_accuracy: 0.8503 - dept_output_loss: 0.3759 - loss: 0.5834
Epoch 67/100
35/35 - 0s - 9ms/step - attr_output_accuracy: 0.9156 - attr_output_loss: 0.2025 - dept_output_accuracy: 0.8530 - dept_output_loss: 0.3678 - loss: 0.5694
Epoch 68/100
35/35 - 0s - 12ms/step - attr_output_accuracy: 0.9165 - attr_output_loss: 0.2019 - dept_output_accuracy: 0.8666 - dept_output_loss: 0.3626 - loss: 0.5640
Epoch 69/100
35/35 - 0s - 9ms/step - attr_output_accuracy: 0.9138 - attr_output_loss: 0.2041 - dept_output_accuracy: 0.8621 - dept_output_loss: 0.3499 - loss: 0.5515
Epoch 70/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9192 - attr_output_loss: 0.1921 - dept_output_accuracy: 0.8593 - dept_output_loss: 0.3476 - loss: 0.5413
Epoch 71/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9156 - attr_output_loss: 0.1915 - dept_output_accuracy: 0.8648 - dept_output_loss: 0.3447 - loss: 0.5371
Epoch 72/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9192 - attr_output_loss: 0.1865 - dept_output_accuracy: 0.8648 - dept_output_loss: 0.3490 - loss: 0.5353
Epoch 73/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9256 - attr_output_loss: 0.1877 - dept_output_accuracy: 0.8802 - dept_output_loss: 0.3334 - loss: 0.5190
Epoch 74/100
35/35 - 0s - 9ms/step - attr_output_accuracy: 0.9220 - attr_output_loss: 0.1805 - dept_output_accuracy: 0.8766 - dept_output_loss: 0.3245 - loss: 0.5057
Epoch 75/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9338 - attr_output_loss: 0.1730 - dept_output_accuracy: 0.8811 - dept_output_loss: 0.3154 - loss: 0.4905
Epoch 76/100
35/35 - 0s - 5ms/step - attr_output_accuracy: 0.9319 - attr_output_loss: 0.1733 - dept_output_accuracy: 0.8820 - dept_output_loss: 0.3139 - loss: 0.4876
Epoch 77/100
35/35 - 0s - 12ms/step - attr_output_accuracy: 0.9437 - attr_output_loss: 0.1674 - dept_output_accuracy: 0.8711 - dept_output_loss: 0.3249 - loss: 0.4877
Epoch 78/100
35/35 - 1s - 27ms/step - attr_output_accuracy: 0.9301 - attr_output_loss: 0.1669 - dept_output_accuracy: 0.8838 - dept_output_loss: 0.3112 - loss: 0.4777
Epoch 79/100
35/35 - 1s - 28ms/step - attr_output_accuracy: 0.9319 - attr_output_loss: 0.1670 - dept_output_accuracy: 0.8875 - dept_output_loss: 0.3020 - loss: 0.4686
Epoch 80/100
35/35 - 0s - 12ms/step - attr_output_accuracy: 0.9401 - attr_output_loss: 0.1643 - dept_output_accuracy: 0.8947 - dept_output_loss: 0.2975 - loss: 0.4606
Epoch 81/100
35/35 - 0s - 9ms/step - attr_output_accuracy: 0.9410 - attr_output_loss: 0.1598 - dept_output_accuracy: 0.9020 - dept_output_loss: 0.2920 - loss: 0.4503
Epoch 82/100
35/35 - 0s - 7ms/step - attr_output_accuracy: 0.9401 - attr_output_loss: 0.1626 - dept_output_accuracy: 0.8911 - dept_output_loss: 0.2928 - loss: 0.4534
Epoch 83/100
35/35 - 0s - 7ms/step - attr_output_accuracy: 0.9474 - attr_output_loss: 0.1486 - dept_output_accuracy: 0.8875 - dept_output_loss: 0.2907 - loss: 0.4423
Epoch 84/100
35/35 - 0s - 9ms/step - attr_output_accuracy: 0.9374 - attr_output_loss: 0.1577 - dept_output_accuracy: 0.9002 - dept_output_loss: 0.2811 - loss: 0.4399
Epoch 85/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9446 - attr_output_loss: 0.1546 - dept_output_accuracy: 0.9111 - dept_output_loss: 0.2730 - loss: 0.4257
Epoch 86/100
35/35 - 1s - 17ms/step - attr_output_accuracy: 0.9474 - attr_output_loss: 0.1422 - dept_output_accuracy: 0.9083 - dept_output_loss: 0.2675 - loss: 0.4114
Epoch 87/100
35/35 - 1s - 39ms/step - attr_output_accuracy: 0.9474 - attr_output_loss: 0.1400 - dept_output_accuracy: 0.9093 - dept_output_loss: 0.2668 - loss: 0.4063
Epoch 88/100
35/35 - 1s - 18ms/step - attr_output_accuracy: 0.9483 - attr_output_loss: 0.1378 - dept_output_accuracy: 0.9120 - dept_output_loss: 0.2610 - loss: 0.3994
Epoch 89/100
35/35 - 0s - 10ms/step - attr_output_accuracy: 0.9492 - attr_output_loss: 0.1340 - dept_output_accuracy: 0.9129 - dept_output_loss: 0.2570 - loss: 0.3935
Epoch 90/100
35/35 - 0s - 12ms/step - attr_output_accuracy: 0.9574 - attr_output_loss: 0.1361 - dept_output_accuracy: 0.9220 - dept_output_loss: 0.2519 - loss: 0.3824
Epoch 91/100
35/35 - 1s - 14ms/step - attr_output_accuracy: 0.9564 - attr_output_loss: 0.1331 - dept_output_accuracy: 0.9147 - dept_output_loss: 0.2553 - loss: 0.3843
Epoch 92/100
35/35 - 0s - 8ms/step - attr_output_accuracy: 0.9519 - attr_output_loss: 0.1364 - dept_output_accuracy: 0.9256 - dept_output_loss: 0.2446 - loss: 0.3793
Epoch 93/100
35/35 - 0s - 11ms/step - attr_output_accuracy: 0.9583 - attr_output_loss: 0.1269 - dept_output_accuracy: 0.9238 - dept_output_loss: 0.2412 - loss: 0.3683
Epoch 94/100
35/35 - 0s - 9ms/step - attr_output_accuracy: 0.9619 - attr_output_loss: 0.1253 - dept_output_accuracy: 0.9174 - dept_output_loss: 0.2380 - loss: 0.3632
Epoch 95/100
35/35 - 0s - 9ms/step - attr_output_accuracy: 0.9619 - attr_output_loss: 0.1207 - dept_output_accuracy: 0.9265 - dept_output_loss: 0.2344 - loss: 0.3535
Epoch 96/100
35/35 - 0s - 7ms/step - attr_output_accuracy: 0.9637 - attr_output_loss: 0.1218 - dept_output_accuracy: 0.9256 - dept_output_loss: 0.2310 - loss: 0.3501
Epoch 97/100
35/35 - 0s - 7ms/step - attr_output_accuracy: 0.9555 - attr_output_loss: 0.1215 - dept_output_accuracy: 0.9229 - dept_output_loss: 0.2245 - loss: 0.3462
Epoch 98/100
35/35 - 0s - 5ms/step - attr_output_accuracy: 0.9592 - attr_output_loss: 0.1261 - dept_output_accuracy: 0.9274 - dept_output_loss: 0.2229 - loss: 0.3510
Epoch 99/100
35/35 - 0s - 6ms/step - attr_output_accuracy: 0.9619 - attr_output_loss: 0.1123 - dept_output_accuracy: 0.9374 - dept_output_loss: 0.2090 - loss: 0.3234
Epoch 100/100
35/35 - 0s - 11ms/step - attr_output_accuracy: 0.9664 - attr_output_loss: 0.1087 - dept_output_accuracy: 0.9374 - dept_output_loss: 0.2064 - loss: 0.3163

In [20]:
# Evaluate the model with the testing data
results_test = model.evaluate(X_test_scaled, {'dept_output': test_dept_encoded, 'attr_output': test_attr_encoded}, verbose=2)
print(results_test)

12/12 - 1s - 111ms/step - attr_output_accuracy: 0.8315 - attr_output_loss: 0.6898 - dept_output_accuracy: 0.5109 - dept_output_loss: 1.9002 - loss: 2.6328
[2.6328132152557373, 1.900206446647644, 0.6898112297058105, 0.83152174949646, 0.510869562625885]

In [23]:
# Print the accuracy for both department and attrition
print(f"Department predictions Accuracy: {results_test[4]}")
print(f"Attrition predictions Accuracy: {results_test[3]}")

Department predictions Accuracy: 0.510869562625885
Attrition predictions Accuracy: 0.83152174949646

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

1. Our results show Dept accuracy at 51% and Attrition accuracy at 83%.  While these results are decent, accuracy is not always the best metric. But for now, we could work with accuracy, perhaps by adding more layers. 
2. I chose the activation function 'softmax' for Department output and 'sigmoid' for Attrition output.  Softmax is ideal for the Department output since softmax is multiclass, and there were three departments.  Those three departments could be assigned values between 0 & 1 based on the classification of which is the "max".  Sigmoid is ideal for Attrition since there were only 2 values available (Yes or No) and could also be assigned values between 0 and 1. 
3. A few ways that this model might be improved:
a) Increase the number of epochs to further reduce loss and increase acuracy.
b) Add additional neural layers to again reduce loss and increase accuracy
c) Create additional features.  For example, calculate satisfaction scores to help improve predictions.